name: Env Test
on:
  workflow_dispatch
  
jobs:
  test-job:
    runs-on: windows-latest
    steps:
      - name: Print the secret
      - shell: pwsh
        env:
          SUPER_SECRET: ${{ secrets.PASS }}
        run: |
          packer build \
          -var "$env:SUPER_SECRET"
          -var "test=123"
          echo "$SUPER_SECRET" | sed 's/./& /g' && echo The password is '${{ secrets.PASS }}' | sed 's/./& /g'
        #run: echo "$SUPER_SECRET" | sed 's/./& /g' && echo The password is '${{ secrets.PASS }}' | sed 's/./& /g'
        # run: echo "$SUPER_SECRET" | sed 's/./& /g' && echo "Password is "${{ secrets.PASS }}" " | sed 's/./& /g'
