name: Env Test
on:
  workflow_dispatch
  
jobs:
  test-job:
    runs-on: windows-latest
    steps:
      - shell: cmd
        env:
          SUPER_SECRET: ${{ secrets.PASS }}
        run: |
          echo "The password is "%SUPER_SECRET%" " | sed 's/./& /g'

        # echo "$SUPER_SECRET" | sed 's/./& /g' && echo "The password is '${{ secrets.PASS }}'" | sed 's/./& /g'
        #run: echo "$SUPER_SECRET" | sed 's/./& /g' && echo The password is '${{ secrets.PASS }}' | sed 's/./& /g'
        # run: echo "$SUPER_SECRET" | sed 's/./& /g' && echo "Password is "${{ secrets.PASS }}" " | sed 's/./& /g'
